const actionTypes = {
  // FETCH_COUNTRIES: 'FETCH_COUNTRIES',
  // FILTER_COUNTRIES: 'FILTER_COUNTRIES',
  // CURRENT_COUNTRIES: 'CURRENT_COUNTRIES',
  FILTER_COUNTRIES_REGION: "FILTER_COUNTRIES_REGION",
  FILTER_COUNTRIES: "FILTER_COUNTRIES",
  SELECT_COUNTRY: "SELECT_COUNTRY",
  DEFAULT_COUNTRIES_SPECIFIC: "DEFAULT_COUNTRIES_SPECIFIC",
  CHANGE_TEXT: "CHANGE_TEXT",
};

export default actionTypes;
